### ISSUE TITLE
Could you please delete this npm package

### ISSUE THREAD

**Issue by AjayTheWizard** [kaizhu256/node-bootstrap-lite#1]
I am currently developing Bootstrap Lite version and I want to publish at name of `bootstrap-lite`. It's different from yours.
Bootstrap:
`bootstrap.css` - `244kb`
`bootstrap.min.css` - `191kb`

My Bootstrap
`bootstrap.lite.css` - `190kb`
`bootstrap.lite.min.css` - `141kb`

Neither Components nor Classes is removed

Could you please delete this npm package So that I can publish in that name.

**Comment by kaizhu256** [comment]
hi @AjayTheWizard, sorry, but i have clients who depend on this package, so can't delete.
